import type { Photobook } from "@/types/book";

export const SAMPLE_PHOTOS = {
  concrete: "/images/concrete.jpg",
  coast: "/images/coast.jpg",
  detail: "/images/detail.jpg",
};

export const sampleBook: Photobook = {
  id: "book_demo",
  slug: "white-coast-study",
  authorId: "user_lin",
  title: "白色海岸练习",
  subtitle: "关于光、墙面与停留",
  author: "林屿",
  description: "一组未标明具体地点的建筑观察。白墙、海风和重复出现的阴影构成了这本摄影书的线索。",
  status: "draft",
  aiEnabled: true,
  commentsEnabled: true,
  updatedAt: new Date().toISOString(),
  document: {
    version: 1,
    backgroundPolicy: "fixed-white",
    pages: [
      {
        id: "page_cover",
        name: "封面",
        format: "4:3",
        width: 1440,
        height: 1080,
        background: "#ffffff",
        transition: "fade",
        elements: [
          {
            id: "cover_image",
            type: "image",
            src: SAMPLE_PHOTOS.concrete,
            name: "混凝土建筑",
            alt: "阳光下的现代建筑立面",
            x: 92,
            y: 86,
            width: 920,
            height: 760,
            rotation: 0,
            opacity: 1,
            fit: "cover",
            location: { city: "地点未公开", visibility: "hidden" },
          },
          {
            id: "cover_dots",
            type: "pattern",
            pattern: "dots",
            x: 1040,
            y: 86,
            width: 300,
            height: 300,
            rotation: 0,
            opacity: 1,
            foreground: "#1d1d1f",
            background: "transparent",
            spacing: 34,
            scale: 1,
          },
          {
            id: "cover_title",
            type: "text",
            text: "白色\n海岸练习",
            x: 1034,
            y: 470,
            width: 320,
            height: 240,
            rotation: 0,
            opacity: 1,
            fontSize: 72,
            fontFamily: "sans",
            fontWeight: 600,
            color: "#111111",
            align: "left",
            lineHeight: 1.14,
          },
          {
            id: "cover_meta",
            type: "text",
            text: "PHOTOGRAPHS / 2026\n林屿",
            x: 1038,
            y: 860,
            width: 290,
            height: 70,
            rotation: 0,
            opacity: 1,
            fontSize: 22,
            fontFamily: "sans",
            fontWeight: 500,
            color: "#4b4b4b",
            align: "left",
            lineHeight: 1.45,
          },
        ],
      },
      {
        id: "page_architecture",
        name: "光与墙面",
        format: "16:9",
        width: 1600,
        height: 900,
        background: "#ffffff",
        transition: "slide-left",
        elements: [
          {
            id: "page2_image",
            type: "image",
            src: SAMPLE_PHOTOS.coast,
            name: "海边住宅",
            alt: "白色建筑与开阔天空",
            x: 80,
            y: 76,
            width: 1040,
            height: 748,
            rotation: 0,
            opacity: 1,
            fit: "cover",
            location: { city: "地点未公开", visibility: "hidden" },
          },
          {
            id: "page2_number",
            type: "text",
            text: "02",
            x: 1200,
            y: 76,
            width: 250,
            height: 80,
            rotation: 0,
            opacity: 1,
            fontSize: 64,
            fontFamily: "serif",
            fontWeight: 400,
            color: "#111111",
            align: "right",
            lineHeight: 1,
          },
          {
            id: "page2_caption",
            type: "text",
            text: "正午以后，墙面把风的方向变成了阴影。\n\n地点并不重要，重要的是人在建筑之间停留了多久。",
            x: 1200,
            y: 420,
            width: 270,
            height: 250,
            rotation: 0,
            opacity: 1,
            fontSize: 28,
            fontFamily: "serif",
            fontWeight: 400,
            color: "#222222",
            align: "left",
            lineHeight: 1.65,
          },
          {
            id: "page2_frame",
            type: "pattern",
            pattern: "frame",
            x: 1170,
            y: 380,
            width: 330,
            height: 340,
            rotation: 0,
            opacity: 0.35,
            foreground: "#111111",
            background: "transparent",
            spacing: 28,
            scale: 1,
          },
        ],
      },
      {
        id: "page_detail",
        name: "住屋细节",
        format: "3:4",
        width: 1080,
        height: 1440,
        background: "#ffffff",
        transition: "wipe",
        elements: [
          {
            id: "page3_image",
            type: "image",
            src: SAMPLE_PHOTOS.detail,
            name: "住宅细节",
            alt: "住宅外观与树木",
            x: 80,
            y: 80,
            width: 920,
            height: 900,
            rotation: 0,
            opacity: 1,
            fit: "cover",
            location: { city: "地点未公开", visibility: "hidden" },
          },
          {
            id: "page3_title",
            type: "text",
            text: "房子记住了\n每一次光线的移动",
            x: 80,
            y: 1050,
            width: 620,
            height: 180,
            rotation: 0,
            opacity: 1,
            fontSize: 54,
            fontFamily: "serif",
            fontWeight: 500,
            color: "#111111",
            align: "left",
            lineHeight: 1.35,
          },
          {
            id: "page3_grid",
            type: "pattern",
            pattern: "grid",
            x: 760,
            y: 1060,
            width: 240,
            height: 240,
            rotation: 0,
            opacity: 0.55,
            foreground: "#111111",
            background: "transparent",
            spacing: 30,
            scale: 1,
          },
        ],
      },
    ],
  },
};

sampleBook.publishedSnapshot = {
  id: "version_demo_public",
  publishedAt: "2026-08-01T10:00:00.000Z",
  document: structuredClone(sampleBook.document),
};
